ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 38, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 42, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:47:47] "POST /diagram_upload HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:49:02] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:58:25] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:58:25] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:58:25] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:58:34] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:58:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2020 23:59:01] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:00:35] "POST /diagram_upload HTTP/1.1" 200 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 61, in diagram_upload
    return render_template("output.html", data=data.split('\n'))
  File "C:\Python38\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Python38\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Projects\diagram2code\templates\output.html", line 28, in template
    {{% for line in data %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:03:38] "POST /diagram_upload HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:04:55] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:07:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:07:05] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:07:05] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:07:16] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:08:25] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:09:42] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:11:49] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:13:09] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:15:51] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:18:05] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:18:14] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:20:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:20:10] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:20:10] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:20:20] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:21:23] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:21:23] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:21:23] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:21:34] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:22:17] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:22:17] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:22:17] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:22:26] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:24:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:24:24] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:24:25] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:24:34] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:26:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:26:17] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:26:17] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:26:19] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:26:30] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:27:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:27:05] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:27:05] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:27:17] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:28:58] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:28:59] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:28:59] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:29:08] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:30:43] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:31:31] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:31:31] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:31:31] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:31:41] "POST /diagram_upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:33:27] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:33:27] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:33:27] "GET /static/resources/logo.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 00:33:39] "POST /diagram_upload HTTP/1.1" 200 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 38, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 42, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:25:20] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 39, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 43, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:32:03] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 39, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 43, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:33:21] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 39, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 43, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:33:31] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 39, in diagram_upload
    try:
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 43, in diagram_upload
    except Exception as e:
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:34:27] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 41, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 45, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:34:44] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 42, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 46, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:36:44] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 42, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 46, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:46:01] "POST /diagram_upload HTTP/1.1" 500 -
ERROR:app:Exception on /diagram_upload [POST]
Traceback (most recent call last):
  File "app.py", line 42, in diagram_upload
    root, root_complete, mxGraphModel, diagram, mxfile, tree = read_drawio_xml(file)
  File "D:\Projects\diagram2code\modules\utils.py", line 71, in read_drawio_xml
    tree = ET.parse(diagram_path)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 46, in diagram_upload
    root_complete = highlight_element(root_complete, trouble_elem_id)
UnboundLocalError: local variable 'root_complete' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [16/Oct/2020 20:46:07] "POST /diagram_upload HTTP/1.1" 500 -
